version: '3'

services:
  postgres:
    container_name: postgres
    image: 'docker.io/postgis/postgis:14-3.3'
    environment:
      - POSTGRES_PASSWORD=ai4ncF6GpHokPaNmW25UftzMjM7hrC
    volumes:
      - './postgres-data:/var/lib/postgresql'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports:
      - '5444:5432'

  redis:
    container_name: redis 
    image: 'docker.io/redis:4.0-alpine'
    command: redis-server --requirepass nuX4X62C49tq
    volumes:
      - './redis-data:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    container_name: website
    build: .
    env_file:
      - '.env'
    volumes:
      - '.:/app'
    links:
      - redis
    ports:
      - '8000:5000'

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - website

  celery:
    container_name: celery
    build: .
    command: celery worker -B -l info -A enferno.tasks
    env_file:
      - '.env'
    links:
      - redis
    volumes:
      - '.:/enferno-plat'

volumes:
  enferno:
  redis:
  db:
